services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_DATABASE: 'apiadopto'
      POSTGRESQL_USERNAME: 'docker'
      POSTGRESQL_PASSWORD: 'docker'
    volumes:
      - ./initPostgreDb.sql:/docker-entrypoint-initdb.d/initPostgreDb.sql